submission: client_pop3.py server_pop3.py sample-email-1.txt sample-email-2.txt sample-email-3.txt makefile
	tar -czvf prog1.zip client_pop3.py server_pop3.py sample-email-1.txt sample-email-2.txt sample-email-3.txt makefile

clean: 
	rm  sample-email-1~received.txt sample-email-2~received.txt sample-email-3~received.txt

